name: project_alter
description: An new Dart Frog application
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  crypto: ^3.0.2
  dart_frog: ^0.3.0
  dart_frog_web_socket: ^0.1.0-dev.3
  dart_jsonwebtoken: ^2.7.1
  dartz: ^0.10.1
  dotenv: ^4.1.0
  jwt_decode: ^0.3.1
  postgres_pool: ^2.1.6

dev_dependencies:
  mocktail: ^0.3.0
  test: ^1.19.2
  very_good_analysis: ^4.0.0
